# Generated by Django 3.2.8 on 2021-10-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Store'), (2, 'End User')], default=2),
        ),
    ]
