# Generated by Django 3.2.8 on 2021-10-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_level',
            new_name='level',
        ),
    ]
